name: Portfolio Health Check

on:
  schedule:
    # Run weekly health check
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check repository health
        run: |
          echo "🔍 Running portfolio health check..."
          
          # Check file sizes
          echo "📊 File size analysis:"
          find . -name "*.css" -exec ls -lh {} \; | awk '{print $5 " " $9}'
          
          # Check for TODO/FIXME comments
          echo "📝 Checking for TODO/FIXME comments:"
          grep -r "TODO\|FIXME\|HACK\|XXX" . --include="*.css" --include="*.html" --include="*.md" || echo "✅ No TODO/FIXME comments found"
          
          # Basic accessibility check
          echo "♿ Basic accessibility check:"
          if find . -name "*.html" -exec grep -l "alt=" {} \; | head -1; then
            echo "✅ Found images with alt attributes"
          else
            echo "⚠️  No alt attributes found in HTML files"
          fi
          
          echo "✅ Health check completed"