name: Essential Portfolio Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  essential-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check README exists
        run: |
          if [ ! -f "README.md" ]; then
            echo "❌ README.md is missing"
            exit 1
          fi
          echo "✅ README.md exists"
          
      - name: Check CSS files
        run: |
          if [ ! -d "assets" ]; then
            echo "❌ Assets directory is missing"
            exit 1
          fi
          echo "✅ Assets directory exists"
          
      - name: Validate HTML structure
        run: |
          if ! grep -q "<!DOCTYPE html>" README.md 2>/dev/null && ! find . -name "*.html" -exec grep -l "<!DOCTYPE html>" {} \; | head -1; then
            echo "⚠️  No HTML files with proper DOCTYPE found"
          else
            echo "✅ HTML structure looks good"
          fi