name: Update GitHub Stats

on:
  schedule:
    # Runs every 6 hours to refresh stats
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Force refresh GitHub stats cache
        shell: bash
        run: |
          echo "Triggering stats refresh at $(date)"
          # Remove old timestamp and add new one to force cache refresh
          sed -i '/<!-- Stats updated:/d' README.md
          echo "<!-- Stats updated: $(date) -->" >> README.md
      - name: Commit changes if any
        shell: bash
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "🔄 Auto-refresh stats $(date +'%Y-%m-%d %H:%M')"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
