name: Windows Compatibility Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-compatibility:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check file encoding
        run: |
          Write-Host "✅ Checking file encodings for Windows compatibility"
          Get-ChildItem -Recurse -Include "*.md", "*.html", "*.css", "*.js" | ForEach-Object {
            $content = Get-Content $_.FullName -Raw -Encoding UTF8
            if ($content -match "[^\x00-\x7F]") {
              Write-Host "⚠️  Non-ASCII characters found in: $($_.Name)"
            }
          }
          
      - name: Check line endings
        run: |
          Write-Host "✅ Checking line endings"
          $files = Get-ChildItem -Recurse -Include "*.md", "*.html", "*.css" | Select-Object -First 5
          foreach ($file in $files) {
            $content = [System.IO.File]::ReadAllBytes($file.FullName)
            $hasCRLF = ($content -join '') -match "`r`n"
            Write-Host "File: $($file.Name) - CRLF: $hasCRLF"
          }